## source("https://bioconductor.org/biocLite.R")
## BiocInstaller::biocLite("IRanges")
## BiocInstaller::biocLite("BiocParallel")

suppressPackageStartupMessages({
    library(haven)
    library(readr)
    library(dplyr)
    library(IRanges)
    library(stringdist)
    library(purrr)
    library(tidyr)
    library(tibble)
    library(msm)
    library(abind)
    library(BiocParallel)
})
